### ISSUE TITLE
JumpCloud Support Link and Document History Update

### ISSUE THREAD

**Issue by davidferguson-cr** [awsdocs/aws-single-sign-on-user-guide#14]
JumpCloud appears to have been added as a supported Identity Provider (https://docs.aws.amazon.com/singlesignon/latest/userguide/jumpcloud-idp.html), however this page does not exist in the index (`doc_source/index.md`) nor the Document History (`doc_source/document-history.md`).

Please can these be fixed?

`doc_source/jumpcloud-idp.md` has not been merged to this repo and I don't know the release date, so I am unable to raise a PR.

**Comment by sophjaco** [comment]
Hi, https://github.com/awsdocs/aws-single-sign-on-user-guide has been updated. Thank you for your feedback.
