### ISSUE TITLE
Additional permissions required to use the IAM Identity Center console

### ISSUE THREAD

**Issue by zjt** [awsdocs/aws-single-sign-on-user-guide#16]
For a user to work with the IAM Identity Center console without errors, additional permissions are required, in addition to the permissions that are documented. Without these additional permissions the console does not load.
```
                "iam:ListPolicies",
                "access-analyzer:ValidatePolicy",
                "organizations:ListRoots",
                "organizations:ListAccounts",
                "organizations:ListOrganizationalUnitsForParent",
                "organizations:ListAccountsForParent",
                "organizations:DescribeOrganization",
                "organizations:ListChildren",
                "organizations:DescribeAccount",
                "organizations:ListParents",
```
These additional permissions were determined by CloudTrail analysis and may not be completely least privilege.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
