### ISSUE TITLE
Reset User's Password option doesn't exist

### ISSUE THREAD

**Issue by peakematt** [awsdocs/aws-single-sign-on-user-guide#19]
Hello! I was working to reset a user's password in Identity Center, but I don't think the option to reset a password exists on the user detail page [like the docs suggest](https://github.com/awsdocs/aws-single-sign-on-user-guide/blob/c10c54b635b5625b2df1c4ef6a3b808317415308/doc_source/resetuserpwd.md?plain=1#L13)? 

Am I missing it? 

We're using the built-in identity source so no AD, no SAML federation, etc. 

Thank you!

![image](https://user-images.githubusercontent.com/7741049/230604577-67d92c48-3adb-4fde-9ab3-d4a0ad367757.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
