### ISSUE TITLE
How to Enable MFA

### ISSUE THREAD

**Issue by pcolmer** [awsdocs/aws-single-sign-on-user-guide#4]
The documentation says to open the AWS SSO console then choose Settings > Configure > Configure authentication.

That option isn't displayed for me.

I suspect that this is because I've configured AWS SSO to use an external identity provider. I think that AWS SSO MFA will only work with AWS SSO as the identity source.

**Comment by nicholaspierson** [comment]
Hi Phillip, thanks for your comment. We have a note in the Considerations section https://docs.aws.amazon.com/singlesignon/latest/userguide/enable-mfa.html#mfa-considerations that calls out that external IdPs are not supported for use with MFA in AWS SSO. Thanks.
